# Generated by Django 5.0.2 on 2024-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_channel_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='memeber',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
