# Generated by Django 5.0.2 on 2024-03-03 16:27

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_channel_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=server.models.category_icon_upload_path),
        ),
    ]
